//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidyoIntegration.VidyoService.VidyoPortalGuestService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class InvalidArgumentFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class ResourceNotAvailableFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class GeneralFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class RoomIsFullFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class AccessRestrictedFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class ConferenceLockedFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class WrongPinFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class AllLinesInUseFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://portal.vidyo.com/guest", ConfigurationName="VidyoPortalGuestService.VidyoPortalGuestServicePortType")]
    public interface VidyoPortalGuestServicePortType {
        
        // CODEGEN: Generating message contract since the operation logInAsGuest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="logInAsGuest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.InvalidArgumentFault), Action="logInAsGuest", Name="InvalidArgumentFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.ResourceNotAvailableFault), Action="logInAsGuest", Name="ResourceNotAvailableFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.GeneralFault), Action="logInAsGuest", Name="GeneralFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.RoomIsFullFault), Action="logInAsGuest", Name="RoomIsFullFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestResponse1 logInAsGuest(VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="logInAsGuest", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestResponse1> logInAsGuestAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1 request);
        
        // CODEGEN: Generating message contract since the operation linkEndpointToGuest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="linkEndpointToGuest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.AccessRestrictedFault), Action="linkEndpointToGuest", Name="AccessRestrictedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.InvalidArgumentFault), Action="linkEndpointToGuest", Name="InvalidArgumentFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.GeneralFault), Action="linkEndpointToGuest", Name="GeneralFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestResponse1 linkEndpointToGuest(VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="linkEndpointToGuest", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestResponse1> linkEndpointToGuestAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1 request);
        
        // CODEGEN: Generating message contract since the operation guestJoinConference is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="guestJoinConference", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.InvalidArgumentFault), Action="guestJoinConference", Name="InvalidArgumentFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.ResourceNotAvailableFault), Action="guestJoinConference", Name="ResourceNotAvailableFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.GeneralFault), Action="guestJoinConference", Name="GeneralFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.RoomIsFullFault), Action="guestJoinConference", Name="RoomIsFullFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.ConferenceLockedFault), Action="guestJoinConference", Name="ConferenceLockedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.WrongPinFault), Action="guestJoinConference", Name="WrongPinFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.AllLinesInUseFault), Action="guestJoinConference", Name="AllLinesInUseFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceResponse1 guestJoinConference(VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="guestJoinConference", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceResponse1> guestJoinConferenceAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getPortalVersion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getPortalVersion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalGuestService.GeneralFault), Action="getPortalVersion", Name="GeneralFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionResponse1 getPortalVersion(VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getPortalVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionResponse1> getPortalVersionAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class LogInAsGuestRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string roomKeyField;
        
        private string guestNameField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string roomKey {
            get {
                return this.roomKeyField;
            }
            set {
                this.roomKeyField = value;
                this.RaisePropertyChanged("roomKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string guestName {
            get {
                return this.guestNameField;
            }
            set {
                this.guestNameField = value;
                this.RaisePropertyChanged("guestName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class LogInAsGuestResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int guestIDField;
        
        private bool isLockedField;
        
        private bool hasPinField;
        
        private string vmaddressField;
        
        private string proxyaddressField;
        
        private string loctagField;
        
        private string unField;
        
        private string pakField;
        
        private string portalField;
        
        private string portalVersionField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int guestID {
            get {
                return this.guestIDField;
            }
            set {
                this.guestIDField = value;
                this.RaisePropertyChanged("guestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
                this.RaisePropertyChanged("isLocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool hasPin {
            get {
                return this.hasPinField;
            }
            set {
                this.hasPinField = value;
                this.RaisePropertyChanged("hasPin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string vmaddress {
            get {
                return this.vmaddressField;
            }
            set {
                this.vmaddressField = value;
                this.RaisePropertyChanged("vmaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string proxyaddress {
            get {
                return this.proxyaddressField;
            }
            set {
                this.proxyaddressField = value;
                this.RaisePropertyChanged("proxyaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string loctag {
            get {
                return this.loctagField;
            }
            set {
                this.loctagField = value;
                this.RaisePropertyChanged("loctag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string un {
            get {
                return this.unField;
            }
            set {
                this.unField = value;
                this.RaisePropertyChanged("un");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string pak {
            get {
                return this.pakField;
            }
            set {
                this.pakField = value;
                this.RaisePropertyChanged("pak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string portal {
            get {
                return this.portalField;
            }
            set {
                this.portalField = value;
                this.RaisePropertyChanged("portal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string portalVersion {
            get {
                return this.portalVersionField;
            }
            set {
                this.portalVersionField = value;
                this.RaisePropertyChanged("portalVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=10)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logInAsGuestRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestRequest LogInAsGuestRequest;
        
        public logInAsGuestRequest1() {
        }
        
        public logInAsGuestRequest1(VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestRequest LogInAsGuestRequest) {
            this.LogInAsGuestRequest = LogInAsGuestRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logInAsGuestResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestResponse LogInAsGuestResponse;
        
        public logInAsGuestResponse1() {
        }
        
        public logInAsGuestResponse1(VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestResponse LogInAsGuestResponse) {
            this.LogInAsGuestResponse = LogInAsGuestResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class LinkEndpointToGuestRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int guestIDField;
        
        private string eIDField;
        
        private string vrIPField;
        
        private string clientTypeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int guestID {
            get {
                return this.guestIDField;
            }
            set {
                this.guestIDField = value;
                this.RaisePropertyChanged("guestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EID {
            get {
                return this.eIDField;
            }
            set {
                this.eIDField = value;
                this.RaisePropertyChanged("EID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string vrIP {
            get {
                return this.vrIPField;
            }
            set {
                this.vrIPField = value;
                this.RaisePropertyChanged("vrIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string clientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
                this.RaisePropertyChanged("clientType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class LinkEndpointToGuestResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OK okField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OK OK {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
                this.RaisePropertyChanged("OK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public enum OK {
        
        /// <remarks/>
        OK,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class linkEndpointToGuestRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestRequest LinkEndpointToGuestRequest;
        
        public linkEndpointToGuestRequest1() {
        }
        
        public linkEndpointToGuestRequest1(VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestRequest LinkEndpointToGuestRequest) {
            this.LinkEndpointToGuestRequest = LinkEndpointToGuestRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class linkEndpointToGuestResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestResponse LinkEndpointToGuestResponse;
        
        public linkEndpointToGuestResponse1() {
        }
        
        public linkEndpointToGuestResponse1(VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestResponse LinkEndpointToGuestResponse) {
            this.LinkEndpointToGuestResponse = LinkEndpointToGuestResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class GuestJoinConferenceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int guestIDField;
        
        private string pinField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int guestID {
            get {
                return this.guestIDField;
            }
            set {
                this.guestIDField = value;
                this.RaisePropertyChanged("guestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class GuestJoinConferenceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OK okField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OK OK {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
                this.RaisePropertyChanged("OK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guestJoinConferenceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceRequest GuestJoinConferenceRequest;
        
        public guestJoinConferenceRequest1() {
        }
        
        public guestJoinConferenceRequest1(VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceRequest GuestJoinConferenceRequest) {
            this.GuestJoinConferenceRequest = GuestJoinConferenceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guestJoinConferenceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceResponse GuestJoinConferenceResponse;
        
        public guestJoinConferenceResponse1() {
        }
        
        public guestJoinConferenceResponse1(VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceResponse GuestJoinConferenceResponse) {
            this.GuestJoinConferenceResponse = GuestJoinConferenceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.vidyo.com/guest")]
    public partial class GetPortalVersionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string portalVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string portalVersion {
            get {
                return this.portalVersionField;
            }
            set {
                this.portalVersionField = value;
                this.RaisePropertyChanged("portalVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPortalVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPortalVersionRequest", Namespace="http://portal.vidyo.com/guest", Order=0)]
        public object GetPortalVersionRequest1;
        
        public getPortalVersionRequest() {
        }
        
        public getPortalVersionRequest(object GetPortalVersionRequest1) {
            this.GetPortalVersionRequest1 = GetPortalVersionRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPortalVersionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.vidyo.com/guest", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.GetPortalVersionResponse GetPortalVersionResponse;
        
        public getPortalVersionResponse1() {
        }
        
        public getPortalVersionResponse1(VidyoIntegration.VidyoService.VidyoPortalGuestService.GetPortalVersionResponse GetPortalVersionResponse) {
            this.GetPortalVersionResponse = GetPortalVersionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VidyoPortalGuestServicePortTypeChannel : VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VidyoPortalGuestServicePortTypeClient : System.ServiceModel.ClientBase<VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType>, VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType {
        
        public VidyoPortalGuestServicePortTypeClient() {
        }
        
        public VidyoPortalGuestServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VidyoPortalGuestServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VidyoPortalGuestServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VidyoPortalGuestServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestResponse1 VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.logInAsGuest(VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1 request) {
            return base.Channel.logInAsGuest(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestResponse logInAsGuest(VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestRequest LogInAsGuestRequest) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1();
            inValue.LogInAsGuestRequest = LogInAsGuestRequest;
            VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).logInAsGuest(inValue);
            return retVal.LogInAsGuestResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestResponse1> VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.logInAsGuestAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1 request) {
            return base.Channel.logInAsGuestAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestResponse1> logInAsGuestAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.LogInAsGuestRequest LogInAsGuestRequest) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.logInAsGuestRequest1();
            inValue.LogInAsGuestRequest = LogInAsGuestRequest;
            return ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).logInAsGuestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestResponse1 VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.linkEndpointToGuest(VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1 request) {
            return base.Channel.linkEndpointToGuest(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestResponse linkEndpointToGuest(VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestRequest LinkEndpointToGuestRequest) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1();
            inValue.LinkEndpointToGuestRequest = LinkEndpointToGuestRequest;
            VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).linkEndpointToGuest(inValue);
            return retVal.LinkEndpointToGuestResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestResponse1> VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.linkEndpointToGuestAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1 request) {
            return base.Channel.linkEndpointToGuestAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestResponse1> linkEndpointToGuestAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.LinkEndpointToGuestRequest LinkEndpointToGuestRequest) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.linkEndpointToGuestRequest1();
            inValue.LinkEndpointToGuestRequest = LinkEndpointToGuestRequest;
            return ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).linkEndpointToGuestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceResponse1 VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.guestJoinConference(VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1 request) {
            return base.Channel.guestJoinConference(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceResponse guestJoinConference(VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceRequest GuestJoinConferenceRequest) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1();
            inValue.GuestJoinConferenceRequest = GuestJoinConferenceRequest;
            VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).guestJoinConference(inValue);
            return retVal.GuestJoinConferenceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceResponse1> VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.guestJoinConferenceAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1 request) {
            return base.Channel.guestJoinConferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceResponse1> guestJoinConferenceAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.GuestJoinConferenceRequest GuestJoinConferenceRequest) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.guestJoinConferenceRequest1();
            inValue.GuestJoinConferenceRequest = GuestJoinConferenceRequest;
            return ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).guestJoinConferenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionResponse1 VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.getPortalVersion(VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest request) {
            return base.Channel.getPortalVersion(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalGuestService.GetPortalVersionResponse getPortalVersion(object GetPortalVersionRequest1) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest();
            inValue.GetPortalVersionRequest1 = GetPortalVersionRequest1;
            VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).getPortalVersion(inValue);
            return retVal.GetPortalVersionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionResponse1> VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType.getPortalVersionAsync(VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest request) {
            return base.Channel.getPortalVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionResponse1> getPortalVersionAsync(object GetPortalVersionRequest1) {
            VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest inValue = new VidyoIntegration.VidyoService.VidyoPortalGuestService.getPortalVersionRequest();
            inValue.GetPortalVersionRequest1 = GetPortalVersionRequest1;
            return ((VidyoIntegration.VidyoService.VidyoPortalGuestService.VidyoPortalGuestServicePortType)(this)).getPortalVersionAsync(inValue);
        }
    }
}
